### PR TITLE
REDCORE-495_problem_with_j25

### PR DESCRIPTION
**Pull request by Kixo**

### CODE REVIEW

**Comment by puneet0191** [comment]
@Kixo I looked at the build, it fails at the same line that you added as one of the commits 
```
$I->waitForText("Payment API options",30,{"css":"a"})
```
https://travis-ci.org/redCOMPONENT-COM/redCORE/jobs/158072476#L1070,

**Comment by Kixo** [comment]
that was also a try to fix the problem, as it seems it cannot find "Webservice options" link. I have removed it now and it is the same

**Comment by puneet0191** [comment]
Oh okay, I understand, not sure why Web services Option is not visible. lets see

**Comment by puneet0191** [comment]
Same problem again :confused:

**Pull request merged**
