### PR TITLE
[Improve] Layout for fully support BS3

### PR DESCRIPTION
**Pull request by thongredweb**

### CODE REVIEW

**Comment by thongredweb** [comment]
Configuration page:
redcore-configuration

**Comment by thongredweb** [comment]
Translation page:
redcore-translation

**Comment by Kixo** [comment]
please recheck the conflicts @thongredweb

**Comment by thongredweb** [comment]
@Kixo How about this PR? Is this require more modify or?
In my side, this PR is ready for merge :)

**Comment by Kixo** [comment]
n1 @thongredweb

**Pull request merged**
