### PR TITLE
Add possibility extend classes, which registered from RLoader

### PR DESCRIPTION
**Pull request by shandak**

### CODE REVIEW

**Comment by shandak** [comment]
@Kixo may you help look at it, why travis was fail here? I installed it successfull in the joomla 3.

**Comment by shandak** [comment]
This is error looks werid, I didn't find function `$I->doAdministratorLogin();`, where happened current fail test.
 So I suppose redCORE travis tests was broken?

**Comment by Kixo** [comment]
no it should not be broken, just yesterday we merged a PR

**Comment by shandak** [comment]
@jatitoam I chekced current code in the sc-sound. All overrided fine, so after this redCORE update - we can ubdate B2B safety

**Pull request merged**
