### PR TITLE
Remove language installation from manifests

### PR DESCRIPTION
**Pull request by phproberto**
This removes the languages sections form extensions manifests.

It also changes media from:

```xml
<media destination="mod_redcore_language_switcher" folder="media">
    <folder>css</folder>
</media>
```

to:

```xml
<media folder="media">
    <folder>mod_redcore_language_switcher</folder>
</media>
```

So if in the future we add a JS, fonts, images folder to the media we don't need to change manifest.

### CODE REVIEW

**Comment by javigomez** [comment]
Seems that webservices are failing. See:

screen shot 2015-10-02 at 14 24 45

Not sure how this pull affects Could you check:

```
1) Failed to delete a new contact in com_contacts using delete in AdministratorContacts1Cest::delete (tests/api//administrator.contact.1.0.0.Cest.php)

 Step  I see response contains ""message":"Item not found with given key.","code":404,"type":"Exception""
 Fail  REST response contains
Failed asserting that '{"message":"LIB_REDCORE_API_HAL_WEBSERVICE_ERROR_NO_CONTENT","code":404,"type":"Exception"}' contains ""message":"Item not found with given key.","code":404,"type":"Exception"".

Scenario Steps:

 7. $I->seeResponseContains(""message":"Item not found with given key.","code":404,"type":"Exception"")
 6. $I->seeResponseIsJson()
 5. $I->seeResponseCodeIs(404)
 4. $I->sendGET("index.php?option=contact&api=Hal&webserviceClient=administrator&webserviceVersion=1.0.0&id=1")
 3. $I->seeResponseCodeIs(200)
 2. $I->sendDELETE("index.php?option=contact&api=Hal&webserviceClient=administrator&webserviceVersion=1.0.0&id=1")
```

From what I can see is that this language constant is not anymore translated:

screen shot 2015-10-02 at 14 29 56

**Comment by Kixo** [comment]
this is what this PR is about actually :) placing language into the extension folder, maybe some manual language load is affecting it... @phproberto can you check that?

**Comment by phproberto** [comment]
Nice test :)

I have tested that the language was loaded but as @Kixo says it's related for sure with the change. I'll double check everything.

Thanks!

**Comment by phproberto** [comment]
Change the library language method to use the library folder. Let's see what travis says.

**Comment by phproberto** [comment]
Any news about this?

**Comment by Kixo** [comment]
didn't see that this have passed the test...

**Pull request merged**
