### PR TITLE
QA-8 wait for Selenium server to load

### PR DESCRIPTION
**Pull request by javigomez**
This pull improves the waiting time for Selenium Server to load

### CODE REVIEW

**Comment by javigomez** [comment]
cc: @puneet0191

**Comment by puneet0191** [comment]
I think the problem was not getting the server, it was starting the server so that It is ready to shoot the commands in the browser.

**Comment by javigomez** [comment]
works:

screen shot 2015-01-02 at 17 42 02

screen shot 2015-01-02 at 17 43 09

**Comment by puneet0191** [comment]
:+1: Thanks Javi Merging :smile:

**Pull request merged**
