### PR TITLE
REDSHOP-2025 #comment Move MVC Override plugin to it's own repo

### PR DESCRIPTION
**Pull request by shandak**

### CODE REVIEW

**Comment by jatitoam** [comment]
+1 for this one, can we merge it @Kixo? :)

**Comment by Kixo** [comment]
somehow I overlooked this one :)

**Comment by Kixo** [comment]
btw, should we not install this plugin by default then? https://github.com/redCOMPONENT-COM/redCORE/blob/develop/redcore.xml#L84 If it is not pulled through submodule...

**Comment by jatitoam** [comment]
actually it is :) https://github.com/redCOMPONENT-COM/redCORE/pull/390/files#diff-8903239df476d7401cf9e76af0252622R4

**Pull request merged**
