### PR TITLE
RSBTB-2726 #comment fix bug with wrong total items fo WS, when not set all conditions

### PR DESCRIPTION
**Pull request by shandak**

### CODE REVIEW

**Comment by shandak** [comment]
Another way for discuss: if we call getItemWS first, then getTotal should get thats flag from getItemWS. But then anyway need change in redCORE.
so if we move getTotal https://github.com/redCOMPONENT-COM/redCORE/blob/develop/extensions/libraries/redcore/api/hal/hal.php#L571-L601 after https://github.com/redCOMPONENT-COM/redCORE/blob/develop/extensions/libraries/redcore/api/hal/hal.php#L605 i think it should help too.

**Comment by Kixo** [comment]
yeah, maybe just move it below... I think we recently had some discussion about that if it should go before or after... but decided it has no difference so we put it above, if it solves the problem, maybe we can put it below.

**Comment by shandak** [comment]
I move getTotal after getItem and it works as expected too :)

**Comment by jatitoam** [comment]
very nice update :) thankfully you found a simple way to do it

**Pull request merged**
