### PR TITLE
[fix] using wrong name to disable mootools in system plugin settings

### PR DESCRIPTION
**Pull request by julienV**

### CODE REVIEW

**Comment by julienV** [comment]
not much to explain ;)

**Comment by Kixo** [comment]
:)

**Comment by julienV** [comment]
by the way, i had a hard time finding out that mootools is automatically disabled if the framework is bs3... not sure if it's by design.

**Comment by julienV** [comment]
just looked it up: it is by design
https://github.com/redCOMPONENT-COM/redCORE/blob/develop/extensions/libraries/redcore/html/media.php#L69

but nor sure if it's documented...

**Pull request merged**
