### PR TITLE
REDCORE-355 Adds redCORE download link in documentation

### PR DESCRIPTION
**Pull request by javigomez**
This pull adds a download link to latest redCORE.

Also redCORE is not anymore just a Framework for building extensions but a Joomla Extension that adds webservices, translation feature, MVC override and a Framework for building extensions.  This is now clarified in the documentation

### CODE REVIEW

**Comment by Kixo** [comment]
you forgot it offers SOAP protocol now :)

**Comment by javigomez** [comment]
right! :+1:  adding it. Just a sec.

**Comment by javigomez** [comment]
As agreed in the chat, I'm leaving this pull as it is to be improved later in other pulls with SOAP documentation.

**Comment by Kixo** [comment]
we will add other docs later, this is good as it is for now...

**Pull request merged**
