### PR TITLE
Redcore 446 restructure redcore update gulp

### PR DESCRIPTION
**Pull request by Kixo**
so... what is in here... I restructured it according to this discussion here: https://redweb.atlassian.net/wiki/display/REDRAD/questions/65568976/change-structure-of-redcore-files-and-folders
So I moved all tools and other helper files into the build folder
documentation into the docs folder, tests into tests
and everything that is needed for extension in extension folder...

I have also updated many libraries (js/css) while doing the restructure....

I also removed gulp-redcore from required node modules and placed it into this repo as discussed earlier.
For gulp I also introduced special cases for watching/copying webservices and CLI scripts....
There is a new gulp config dist file so please update your own file so it doesn't loose some new features added in it....

I still need to update docs and other related things....

I did not touch PHING files yet.

### CODE REVIEW

**Comment by Kixo** [comment]
the structure looks like this: 
image

**Comment by Kixo** [comment]
the structure looks like this 
image

**Comment by jatitoam** [comment]
Looks great man

Just one detail for discussion: should we consider keeping gulp-config.json and build.properties files under root so they're easier to find? (I know it's a build topic and I understand the current logic)

**Comment by jatitoam** [comment]
A couple things that catch my attention:
1. .gitignore file needs to be updated
2. I don't see any update to phing/gulp scripts now that they're under the `build` folder.  I guess they didn't need any?

**Comment by Kixo** [comment]
I have kicked as much as possible from the root, so gulp-config.json and build.properties are in a build folder, it is used by the tools so I think they belong in build folder...

**Comment by Kixo** [comment]
1. .I didnt touch .gitignore file, but I will now :)
2. I updated gulp scripts a lot, but I didnt touch PHING. I will update phing scripts as the last thing after this is PR have no other objections :)

**Comment by javigomez** [comment]
I found one of the issues: 

Is generating the Joomla site in a wrong folder:

screen shot 2015-11-24 at 10 15 46

I'm checking it.

**Comment by phproberto** [comment]
I love it :)

The only thing I don't like is the build/media distribution. I think that should be done by extension. Something like:

`build/media/lib_redcore`

and put there the assets for it. In the `extensions` folder the media would be moved inside the library which I think is the right place for it. It should be installed with it.

**Comment by Kixo** [comment]
hmm... can you explain a bit further Roberto, I might be one sided atm so I might not get what you mean...
How I imagined it:
In build/media we have all sorts of media related tools like LESS, SASS which would generate our *.css and *.min.css, then we have css folder and js folder which are in fact css and js folders from our extensions but full non-minified files which are then copied into the extensions media folder so we can have a clean install folder there...
last folder is build/media/lib folder where we put all external libraries (css,js,fonts,imgs...), from here we minimize js/css files and put them into extension/media/lib folder, so anything you drop in here will end up minified (fonts and imgs are copied) in the extension folder ready for use...
dev doesn't have to worry about paths or minification, it is done for him... That was what I was going for...

**Comment by javigomez** [comment]
mmm now it complains for this:

screen shot 2015-11-24 at 16 11 52

**Comment by phproberto** [comment]
Yes @Kixo the concept is the same but in an extension you can have different assets depending on each sub-extension. 

So the redCORE library would have its assets in:
`build/media/libraries/redcore`
and a module in 
`build/media/modules/site/mod_language_switcher`

That's why I think we need different folders there. To avoid mixing assets of all the extensions

**Comment by phproberto** [comment]
See https://bitbucket.org/redwebdk/mipayway/src/f07c9bc5cd8ce75fc7f96312ba38e03d3388f873/src/assets/?at=master

**Comment by Kixo** [comment]
ok now I get what you mean, that's actually very clever :) I will implement it...

**Comment by Kixo** [comment]
ok, your suggestions are implemented @phproberto , I also put couple of improvements into the PR...
also it is not called extension/component/admin but extensions/components/com_redcore/admin now...

**Comment by phproberto** [comment]
Looks good here. Great job @Kixo ! :)

**Comment by Kixo** [comment]
thanks @phproberto :)

**Comment by javigomez** [comment]
Looking good too. 

I have added a pull at https://github.com/Kixo/redCORE/pull/15 but can be added a later.

Excelent job :+1:

**Pull request merged**
