### PR TITLE
Support multiple keys for redcore table class

### PR DESCRIPTION
**Pull request by shandak**

### CODE REVIEW

**Comment by javigomez** [comment]
Tests fail on webservice contact creation:

screen shot 2015-08-03 at 09 54 00

**Comment by shandak** [comment]
@javigomez so its my fault? What you think?

**Comment by javigomez** [comment]
It must be related, yes. The webservice uses that table class to do the create

**Comment by jatitoam** [comment]
@Kixo I'm ok with this one, do you have any comment about it?  Or can we merge it

**Comment by Kixo** [comment]
yes we can :)

**Comment by jatitoam** [comment]
Thanks man

**Pull request merged**
